name: test push

on:
  push:
  

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: echo Test
        run: |
         echo succes push

     
