name: Auto Merge to Master

on:
  push:
    branches:
      - Xavier

jobs:
  merge-to-master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Merge to main
        run: |
          git config user.name "Xavier8L"
          git config user.email "Shenglongchen99@gmail.com"
          git checkout main
          git pull
          git merge --no-ff ${{ github.event.ref }}
          git push main

       
      - name: merge success
        run: |
          echo merge success
